default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV["PG_UN"] %>
  password: <%= ENV["PG_PW"] %>


development:
  <<: *default
  database: home3_development
  #username: home3
  #password:
  # The TCP port the server listens on. Defaults to 5432.

test:
  <<: *default
  database: home3_test

# As with config/credentials.yml, you never want to store sensitive information,
#
production:
  primary: &primary_production
    <<: *default
    database: home3_production
    username: home3
    password: <%= ENV["HOME3_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: home3_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: home3_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: home3_production_cable
    migrations_paths: db/cable_migrate
